package world.selene.common.network

import world.selene.common.network.packet.*

class PacketRegistrations(private val packetFactory: PacketFactory) {
    fun register() {
        packetFactory.registerPacket(
            1,
            AuthenticatePacket::class,
            AuthenticatePacket::encode,
            AuthenticatePacket::decode
        )
        packetFactory.registerPacket(
            2,
            NameIdMappingsPacket::class,
            NameIdMappingsPacket::encode,
            NameIdMappingsPacket.Companion::decode
        )
        packetFactory.registerPacket(
            3,
            MapChunkPacket::class,
            MapChunkPacket::encode,
            MapChunkPacket::decode
        )
        packetFactory.registerPacket(
            4,
            EntityPacket::class,
            EntityPacket::encode,
            EntityPacket.Companion::decode
        )
        packetFactory.registerPacket(
            5,
            SetCameraPositionPacket::class,
            SetCameraPositionPacket.Companion::encode,
            SetCameraPositionPacket.Companion::decode
        )
        packetFactory.registerPacket(
            6,
            SetCameraFollowEntityPacket::class,
            SetCameraFollowEntityPacket.Companion::encode,
            SetCameraFollowEntityPacket.Companion::decode
        )
        packetFactory.registerPacket(
            7,
            SetControlledEntityPacket::class,
            SetControlledEntityPacket.Companion::encode,
            SetControlledEntityPacket.Companion::decode
        )
        packetFactory.registerPacket(
            8,
            RequestMovePacket::class,
            RequestMovePacket::encode,
            RequestMovePacket::decode
        )
        packetFactory.registerPacket(
            9,
            MoveEntityPacket::class,
            MoveEntityPacket::encode,
            MoveEntityPacket::decode
        )
        packetFactory.registerPacket(
            10,
            RemoveEntityPacket::class,
            RemoveEntityPacket::encode,
            RemoveEntityPacket::decode
        )
        packetFactory.registerPacket(
            11,
            RemoveMapChunkPacket::class,
            RemoveMapChunkPacket::encode,
            RemoveMapChunkPacket::decode
        )
        packetFactory.registerPacket(
            12,
            PlaySoundPacket::class,
            PlaySoundPacket::encode,
            PlaySoundPacket::decode
        )
        packetFactory.registerPacket(
            13,
            StopSoundPacket::class,
            StopSoundPacket::encode,
            StopSoundPacket::decode
        )
        packetFactory.registerPacket(
            14,
            UpdateMapTilesPacket::class,
            UpdateMapTilesPacket::encode,
            UpdateMapTilesPacket::decode
        )
        packetFactory.registerPacket(
            15,
            PreferencesPacket::class,
            PreferencesPacket::encode,
            PreferencesPacket::decode
        )
        packetFactory.registerPacket(
            16,
            FinalizeJoinPacket::class,
            FinalizeJoinPacket::encode,
            FinalizeJoinPacket::decode
        )
        packetFactory.registerPacket(
            17,
            TurnEntityPacket::class,
            TurnEntityPacket::encode,
            TurnEntityPacket::decode
        )
        packetFactory.registerPacket(
            18,
            EntityAnimationPacket::class,
            EntityAnimationPacket::encode,
            EntityAnimationPacket::decode
        )
        packetFactory.registerPacket(
            19,
            RequestFacingPacket::class,
            RequestFacingPacket::encode,
            RequestFacingPacket::decode
        )
        packetFactory.registerPacket(
            20,
            NotifyBundleUpdatePacket::class,
            NotifyBundleUpdatePacket::encode,
            NotifyBundleUpdatePacket.Companion::decode
        )
        packetFactory.registerPacket(
            254,
            CustomPayloadPacket::class,
            CustomPayloadPacket::encode,
            CustomPayloadPacket::decode
        )
        packetFactory.registerPacket(255, DisconnectPacket::class, DisconnectPacket::encode, DisconnectPacket::decode)
    }
}