# suppress inspection "UnusedProperty" for whole file

# Enable vertical sync for rendering.
vsync=true

# Enable hot reloading of bundles when files change. Accepted values: false, true, eager.
hot_reload=true

# Override the CEF UI to display. Useful for testing UI from local development servers.
browser_ui_url=

# DEVELOPMENT ONLY: disable CEF web security, CSP, and local-network checks for browser_ui_url.
browser_ui_insecure=false

# Whether CEF should be loaded at all, and where from. These options should probably go to system.properties in the future.
browser_ui_enabled=true
cef_install_dir=jcef-bundle
